// packages/router/src/react/link.tsx
import clsx from 'clsx'
import { useUnit } from 'effector-react'
import React, { AnchorHTMLAttributes, ForwardedRef, forwardRef } from 'react'

import { useRouter } from '../shared/router-provider.tsx'
import { buildPath, RouteInstance, RouteParams, RouteQuery } from '../core'

export type LinkProps<Params extends RouteParams> = {
  to: RouteInstance<Params> | string
  params?: Params
  query?: RouteQuery
  className?: string
  activeClassName?: string
  inactiveClassName?: string
} & AnchorHTMLAttributes<HTMLAnchorElement>

const LinkView = <Params extends RouteParams>(props: LinkProps<Params>, ref: ForwardedRef<HTMLAnchorElement>) => {
  const { to, params, query, activeClassName, inactiveClassName, ...linkProps } = props
  if (typeof props.to === 'string') {
    return <NormalLink ref={ref} href={props.to} {...linkProps} className={clsx(props.className)} />
  }
  // @ts-expect-error
  return <RouteLink ref={ref} {...props} />
}

const NormalLink = forwardRef<HTMLAnchorElement, AnchorHTMLAttributes<HTMLAnchorElement>>((props, ref) => {
  return <a ref={ref} className={props.className} {...props} />
})

const RouteLinkView = <Params extends RouteParams>(
  props: Exclude<LinkProps<Params>, 'to'> & { to: RouteInstance<Params> },
  ref: ForwardedRef<HTMLAnchorElement>
) => {
  const { to, params, query, className, activeClassName, inactiveClassName, onClick, children, target, ...linkProps } =
    props

  const router = useRouter()
  const routeObj = router.routes.find((routeObj) => routeObj.route === to)

  if (!routeObj) {
    throw new Error('[RouteLink] Route not found')
  }

  const [isOpened, navigate] = useUnit([routeObj.route.$isOpened, to.navigate])

  const href = buildPath({
    pathCreator: routeObj.path,
    params: params || {},
    query: query || {},
  })

  return (
    <a
      ref={ref}
      href={href}
      {...linkProps}
      className={clsx(className, isOpened ? activeClassName : inactiveClassName)}
      target={target}
      onClick={(evt) => {
        if (onClick) {
          onClick(evt)
        }

        // allow user to prevent navigation
        if (evt.defaultPrevented) {
          return
        }

        // let browser handle "_blank" target and etc
        if (target && target !== '_self') {
          return
        }

        // skip modified events (like cmd + click to open the link in new tab)
        if (evt.metaKey || evt.altKey || evt.ctrlKey || evt.shiftKey) {
          return
        }

        evt.preventDefault()
        navigate({
          params: params || ({} as Params),
          query: query || {},
        })
      }}
    >
      {children}
    </a>
  )
}

const RouteLink = forwardRef(RouteLinkView)

export const RouterLink = forwardRef(LinkView) as <Params extends RouteParams>(
  props: LinkProps<Params> & { ref?: ForwardedRef<HTMLAnchorElement> }
) => ReturnType<typeof LinkView>

// packages/router/src/vue/link.vue
<template>
  <a :href="href" :class="linkClasses" :target="target" v-bind="$attrs" @click="handleClick">
    <slot></slot>
  </a>
</template>

<script setup lang="ts">
import { computed, ComputedRef, PropType, useAttrs } from 'vue'
import clsx from 'clsx'
import { useUnit } from 'effector-vue/composition'
import { buildPath, RouteInstance, RouteParams, RouteQuery } from '../core'
import { useRouter } from '../react'
import { scopeBind } from 'effector'
import { injectDependency } from '@n2m/core-di'
import { RouteObjectInternal } from '../core/types.ts'
import { CurrentEffectorScopeToken } from '@n2m/adapter-effector'

const props = defineProps({
  to: {
    type: [Object, String] as PropType<RouteInstance<RouteParams> | string>,
    required: true,
  },
  params: {
    type: Object as PropType<RouteParams>,
    default: () => ({}),
  },
  query: {
    type: Object as PropType<RouteQuery>,
    default: () => ({}),
  },
  className: {
    type: String,
    default: '',
  },
  activeClassName: {
    type: String,
    default: '',
  },
  inactiveClassName: {
    type: String,
    default: '',
  },
})

const emit = defineEmits(['click'])

const isExternalLink = computed(() => typeof props.to === 'string')

const router = useRouter()
const routeObj = computed(() => {
  if (isExternalLink.value) {
    return null
  }
  return router.routes.find((routeObj) => routeObj.route === props.to)
}) as ComputedRef<RouteObjectInternal<any>>

if (!routeObj.value) {
  console.error('route.obj', routeObj)
  console.error('[RouteLink] Route not found')
}

const isOpened = useUnit(routeObj.value?.route?.$isOpened)
const navigate = computed(() => {
  if (isExternalLink.value) {
    return null
  }

  // @ts-expect-error
  return scopeBind(props.to?.navigate, { scope: injectDependency(CurrentEffectorScopeToken) })
})

const linkClasses = computed(() =>
  clsx(props.className, isOpened.value ? props.activeClassName : props.inactiveClassName)
)

const href = computed(() => {
  if (isExternalLink.value) {
    return props.to as string
  }

  try {
    return buildPath({
      pathCreator: routeObj.value.path,
      params: props.params || {},
      query: props.query || {},
    })
  } catch (e) {
    console.error('[RouteLink] Error while building path', e)
    return ''
  }
})

const attrs = useAttrs()
const target = computed(() => attrs.target as string | undefined)

function handleClick(event: MouseEvent) {
  emit('click', event)

  // if (event.defaultPrevented) {
  //   console.log('defaultPrevented')
  //   return
  // }

  if (target.value && target.value !== '_self') {
    return
  }

  if (event.metaKey || event.altKey || event.ctrlKey || event.shiftKey) {
    return
  }

  event.preventDefault()

  if (isExternalLink.value || !navigate.value) {
    return
  }

  try {
    navigate.value({
      params: props.params || ({} as RouteParams),
      query: props.query || {},
    })
  } catch (e) {
    console.error('[RouteLink] Error while navigating', e)
  }
}
</script>
